# Generated by Django 4.2.6 on 2023-10-20 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_remove_item_quantity_itemorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_oi', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
