# Generated by Django 4.2.6 on 2023-10-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_itemorder_ordered_itemorder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='piture',
            new_name='picture',
        ),
    ]
