# Generated by Django 4.2.6 on 2023-10-26 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_rename_piture_item_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streep_address', models.CharField(max_length=100)),
                ('appartment_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('zip', models.CharField(max_length=100)),
                ('same_billing_address', models.BooleanField(default=False)),
                ('save_info', models.BooleanField(default=False)),
                ('payment_option', models.CharField(choices=[('p', 'Paypal'), ('s', 'Stripe')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_b_a', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
